<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance - {{ $event->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        h1 {
            color: #1f2937;
            border-bottom: 3px solid #10b981;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        h2 {
            color: #4b5563;
            font-size: 14px;
            margin-top: 30px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
            font-weight: bold;
            color: #1f2937;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .event-info {
            background-color: #f0fdf4;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .info-row {
            margin: 5px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <h1>Attendance Report</h1>
    
    <div class="event-info">
        <h2>Event Information</h2>
        <div class="info-row"><strong>Title:</strong> {{ $event->title }}</div>
        <div class="info-row"><strong>Date:</strong> {{ $event->start_date->format('F d, Y h:i A') }}</div>
        <div class="info-row"><strong>Location:</strong> {{ $event->location }}</div>
        <div class="info-row"><strong>Total Attendees:</strong> {{ $attendances->count() }}</div>
        <div class="info-row"><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</div>
    </div>
    
    <h2>Attendance List</h2>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Checked In At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($attendances as $index => $attendance)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $attendance->user->name }}</td>
                    <td>{{ $attendance->user->email }}</td>
                    <td>{{ $attendance->checked_in_at->format('M d, Y h:i A') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; color: #6b7280;">No attendance records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by Event Management System on {{ now()->format('F d, Y') }}</p>
    </div>
</body>
</html>
